### ISSUE TITLE
Refine Simple Signer - PT 2

### ISSUE THREAD

**Issue by rodolfopietro97** [vechain/vechain-sdk-js#798]
Depends on #780 

Refine signer implementation and flow of task #780 

**Checklist**
- [x] Improve Base Signer -> #803 
   * ~Generics transaction input~
   * ~Understand better signature and methods in order to be fully compatible with both ethers and vechian~
   * ~Test every functionality of Simple Signer(100% coverage)~
   * ~Handle edge cases (e.g. missing delegator)~
- [x] Document difference between Signer, Provider and Wallet (now ProviderInternalWallet) in order to have a clear and simple user experience -> #803 

- [x] Add enableDelegation flag into provider and hardhat integration -> https://github.com/vechain/vechain-sdk-js/issues/799
- [x] Modifications of "apps/" if needed
- [x] Modification of "/docs" examples if needed (in order to be inline with new structure)
- [x] Remove old packages references in doc and readmes
- [x]  Deprecate old packages (provider, signer and wallet) from npm registry

**Comment by rodolfopietro97** [comment]
@nwbrettski @victhorbi If you agree we can deprecate packages (last point of checklist) at new release and remove them when we will not in beta anymore. So I can close this task

**Comment by victhorbi** [comment]
Yes, please. @rodolfopietro97 You can proceed with **deprecating** the packages. Let's not commit for any version/date yet for removing them.
